neo4j:
  username: neo4j
  password: neo4j
  host: localhost
  ports:
     bolt: 7687
     http: 7474

ontologies:
  RO: http://purl.obolibrary.org/obo/ro.owl
  BFO: http://purl.obolibrary.org/obo/bfo.owl
  HP: http://purl.obolibrary.org/obo/hp.owl
  GO: http://purl.obolibrary.org/obo/go.owl
  SO: http://purl.obolibrary.org/obo/so.owl

logging:
  level: DEBUG
  format: '[%(filename)s][%(funcName)20s] %(levelname)s: %(message)s'
