configuration:
  output_directory: output_data
  checkpoint: false
  prefix_map:
    # define non-canonical CURIE to IRI mappings
  node_property_predicates:
    # define predicates that are to be treated as direct node properties (for RDF)
  predicate_mappings:
    # map non-canonical predicates to a property name (for RDF)
  property_types:
    # define the type for non-canonical properties for RDF export
  reverse_prefix_map:
    # define IRI to CURIE mappings
  reverse_predicate_mappings:
    # map property names to non-canonical predicates (for RDF)
merged_graph:
  name: Merged Graph
  source:
    sequence-ontology:
      input:
        name: "Sequence Ontology"
        format: owl
        filename:
          - data/so.owl
    hgnc-dataset:
      prefix_map:
        # define non-canonical CURIE to IRI mappings, specifically for this source
      node_property_predicates:
        # define predicates that are to be treated as direct node properties (for RDF), specifically for this source
      predicate_mappings:
        # map non-canonical predicates to a property name (for RDF), specifically for this source
      property_types:
        # define the type for non-canonical properties for RDF export, specifically for this source
      reverse_prefix_map:
        # define IRI to CURIE mappings, specifically for this source
      reverse_predicate_mappings:
        # map property names to non-canonical predicates (for RDF), specifically for this source
      input:
        name: "HGNC"
        format: nt
        filename:
          - data/hgnc.nt
    test-dataset:
      input:
        format: tsv
        compression: tar.gz
        filename:
          - data/test_dataset.tar.gz
        filters:
          node_filters:
            category:
              - biolink:Gene
              - biolink:Disease
          edge_filters:
            edge_label:
              - biolink:contributes_to
    neo-kg:
      input:
        format: neo4j
        uri: http://localhost:7474
        username: neo4j
        password: neo4j
        page_size: 10000
        filters:
          node_filters:
            category:
              - biolink:Gene
              - biolink:Disease
              - biolink:PhenotypicFeature
          edge_filters:
            subject_category:
              - biolink:Gene
              - biolink:Disease
            object_category:
              - biolink:PhenotypicFeature
            edge_label:
              - biolink:interacts_with
              - biolink:has_phenotype
    sparql-kg:
      input:
        format: sparql
        uri: http://localhost/sparql
        filters:
          edge_filters:
            subject_category:
              - biolink:Gene
              - biolink:PhenotypicFeature
            object_category:
              - biolink:Disease
            edge_label:
              - biolink:is_marker_for
              - biolink:has_phenotype
    local-kg:
      input:
        format: json
        filename:
          - local-kg-dump.json
  operations:
    - name: kgx.graph_operations.summarize_graph.generate_graph_stats
      args:
        graph_name: Merged Graph
        filename: merged-kg_stats.yaml
        node_facet_properties:
          - provided_by
        edge_facet_properties:
          - provided_by
  destination:
    merged-kg-tsv:
      format: tsv
      compression: tar.gz
      filename:
        - merged-kg
