---
name: Check Dependencies in Pyproject.toml

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    types: trigger-run-check-dependencies

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      # Remove and rebuild the lock file to ensure tests can run
      # with the latest dependencies
      - name: Install dependencies
        run: |
          rm -rf uv.lock
          uv sync
          docker run --detach --name kgx-neo4j-unit-test -p 8484:7474 -p 8888:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker run --detach --name kgx-neo4j-integration-test -p 7474:7474 -p 7687:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker ps -a

      - name: Wait
        uses: jakejarvis/wait-action@master
        with:
          time: '45s'

      - name: Run tests
        run: uv run make test
