---
name: Check Dependencies in Pyproject.toml

# Controls when the action will run.
on:
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    types: trigger-run-check-dependencies

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.9", "3.10" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: setup python environment
        with:
          python-version: ${{ matrix.python }}

      # this step we remove and rebuild the poetry.lock file to ensure that the tests that follow can be run
      # with the latest dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          rm -rf poetry.lock
          poetry install 
          docker run --detach --name kgx-neo4j-unit-test -p 8484:7474 -p 8888:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker run --detach --name kgx-neo4j-integration-test -p 7474:7474 -p 7687:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker ps -a

      - name: Wait
        uses: jakejarvis/wait-action@master
        with:
          time: '45s'

      - name: Run tests
        run: |
          poetry run make test