name: Build and test documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - fix_docs
  workflow_dispatch:

jobs:
  test_docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry 1.x
        run: pipx install poetry==1.*

      - name: Install dynamic versioning plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction --with docs

      - name: Build docs
        working-directory: docs
        env:
          SPHINXOPTS: "--keep-going"
        run: poetry run make html
