name: Rebuild KGX Schema

# Controls when the action will run
on:
  # Trigger when PRs are merged to master or when manually triggered
  push:
    branches: [master, trapi_sink]
  
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  rebuild-schema:
    runs-on: ubuntu-latest
    
    steps:
      #----------------------------------------------
      #          install poetry
      #----------------------------------------------
      - name: Install Poetry
        run: pipx install poetry
      
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      
      #----------------------------------------------
      #        install project dependencies
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction
      
      #----------------------------------------------
      #           rebuild KGX schema
      #----------------------------------------------
      - name: Rebuild KGX schema
        run: |
          echo "Rebuilding KGX schema..."
          poetry run make schema
      
      #----------------------------------------------
      #           run tests to verify changes
      #----------------------------------------------
      - name: Setup Neo4j Docker for tests
        run: |
          docker run --detach --name kgx-neo4j-unit-test -p 8484:7474 -p 8888:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker run --detach --name kgx-neo4j-integration-test -p 7474:7474 -p 7687:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker ps -a
      
      - name: Wait for Neo4j to start
        uses: jakejarvis/wait-action@master
        with:
          time: '45s'
      
      - name: Run tests
        run: |
          echo "Running tests to verify schema changes..."
          poetry run make test
          # Check exit code
          if [ $? -ne 0 ]; then
            echo "Tests failed after schema regeneration!"
            exit 1
          fi
      
      #----------------------------------------------
      #           commit schema changes
      #----------------------------------------------
      - name: Commit schema changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Create a flag to track if we made any commits
          MADE_COMMITS=false
          
          # Check if there are changes to commit
          if git diff --exit-code --quiet kgx/schema/kgx_complete.yaml; then
            echo "No changes to the schema detected"
          else
            git add kgx/schema/kgx_complete.yaml
            git commit -m "🤖 Automatically rebuild KGX schema [skip ci]" -m "This commit was automatically generated by GitHub Actions"
            git push
            MADE_COMMITS=true
          fi
          
          # Also check for merged schema
          if git diff --exit-code --quiet kgx/schema/kgx_merged.yaml; then
            echo "No changes to the merged schema detected"
          else
            git add kgx/schema/kgx_merged.yaml
            git commit -m "🤖 Update merged KGX schema [skip ci]" -m "This commit was automatically generated by GitHub Actions"
            git push
            MADE_COMMITS=true
          fi
          
          # Check for transformation file changes
          if git diff --exit-code --quiet kgx/schema/transformations/; then
            echo "No changes to transformation files detected"
          else
            git add kgx/schema/transformations/
            git commit -m "🤖 Update schema transformation files [skip ci]" -m "This commit was automatically generated by GitHub Actions"
            git push
            MADE_COMMITS=true
          fi
          
          # If we made any commits, summarize
          if [ "$MADE_COMMITS" = true ]; then
            echo "Schema files have been updated and committed"
          else
            echo "No schema changes were detected"
          fi