name: Run tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    types: trigger-run-tests

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Setup Neo4j Docker
        run: |
          docker run --detach --name kgx-neo4j-unit-test -p 8484:7474 -p 8888:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker run --detach --name kgx-neo4j-integration-test -p 7474:7474 -p 7687:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker run --detach --name kgx-arango-unit-test -p 8529:8529 --env ARANGO_NO_AUTH=1 arangodb
          docker ps -a

      - name: Wait
        uses: jakejarvis/wait-action@master
        with:
          time: '45s'

      - name: Run tests
        run: uv run make test
